import Head from "next/head"
import HomeComponent from "@/components/host/home-component"
import Layout from "@/components/layout/layout-component"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeComponent />
      </Layout>
    </>
  )
}
